DEFINE
	VAR __DS0FilterTable = 
		TREATAS({"'Fact Workforce'[Currently Employed %]"}, 'Workforce %'[Workforce % Fields])

	VAR __DS0FilterTable2 = 
		FILTER(
			KEEPFILTERS(VALUES('Dim Workforce'[Employing entity])),
			NOT(
				'Dim Workforce'[Employing entity] IN {"Nursing Australia",
					"NATIONAL HOME NURSE PTY LIMITED"}
			)
		)

	VAR __DS0FilterTable3 = 
		TREATAS({"Oct 2025"}, 'Dim Extract Date'[Slicer MMM YYYY])

	VAR __ValueFilterDM0 = 
		FILTER(
			KEEPFILTERS(
				SUMMARIZECOLUMNS(
					'Dim Employment Start Date'[MMM YYYY],
					'Dim Employment Start Date'[YYYYMM],
					__DS0FilterTable,
					__DS0FilterTable2,
					__DS0FilterTable3,
					"Count_Currently_Employed", 'Fact Workforce'[Count Currently Employed],
					"Rolling12MonthTurnover", 'Fact Workforce'[Rolling12MonthTurnover],
					"Reporting_Year_Flag", IGNORE('Dim Extract Date'[Reporting Year Flag])
				)
			),
			[Reporting_Year_Flag] = 1
		)

	VAR __DS0Core = 
		SUMMARIZECOLUMNS(
			'Dim Employment Start Date'[MMM YYYY],
			'Dim Employment Start Date'[YYYYMM],
			__DS0FilterTable,
			__DS0FilterTable2,
			__DS0FilterTable3,
			__ValueFilterDM0,
			"Count_Currently_Employed", 'Fact Workforce'[Count Currently Employed],
			"Rolling12MonthTurnover", 'Fact Workforce'[Rolling12MonthTurnover]
		)

	VAR __DS0PrimaryWindowed = 
		TOPN(
			1001,
			__DS0Core,
			'Dim Employment Start Date'[YYYYMM],
			1,
			'Dim Employment Start Date'[MMM YYYY],
			1
		)

EVALUATE
	__DS0PrimaryWindowed

ORDER BY
	'Dim Employment Start Date'[YYYYMM], 'Dim Employment Start Date'[MMM YYYY]