table 'Dim FSP Clients'
	lineageTag: 5c59a878-e52e-4371-97eb-5840e4d722c3

	column ClientId
		dataType: string
		lineageTag: 7ec9d45a-bce2-4958-86d1-31d793787c4c
		summarizeBy: none
		sourceColumn: ClientId

		annotation SummarizationSetBy = Automatic

	column ClientCode
		dataType: string
		lineageTag: e417a0d0-e6cb-4fd0-8dc8-532df1af235a
		summarizeBy: none
		sourceColumn: ClientCode

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: 6104009d-f4ce-4fea-98c5-3b934dce8902
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column MiddleName
		dataType: string
		lineageTag: 9d163af0-bcf6-4215-9c02-bc7b297423cd
		summarizeBy: none
		sourceColumn: MiddleName

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: 8b8b8974-9402-4d92-9470-477565e41133
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column PreferredName
		dataType: string
		lineageTag: f1b3a84d-14f8-4513-8a15-1310b39a4070
		summarizeBy: none
		sourceColumn: PreferredName

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 739d6033-511e-428f-8a63-1aa5b60da0b8
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column FundingType
		dataType: string
		lineageTag: dd112e28-016b-4036-9991-c46966b0d13f
		summarizeBy: none
		sourceColumn: FundingType

		annotation SummarizationSetBy = Automatic

	column ClientType
		dataType: string
		lineageTag: 8b1979b9-89fc-4860-ada6-11d3f162652b
		summarizeBy: none
		sourceColumn: ClientType

		annotation SummarizationSetBy = Automatic

	column Address1
		dataType: string
		lineageTag: 8a971a53-0562-4c5a-b7f7-5351dfffa5ab
		summarizeBy: none
		sourceColumn: Address1

		annotation SummarizationSetBy = Automatic

	column Address2
		dataType: string
		lineageTag: 3c7f3959-c3de-413f-9c37-c53c26937e87
		summarizeBy: none
		sourceColumn: Address2

		annotation SummarizationSetBy = Automatic

	column Suburb
		dataType: string
		lineageTag: f420797f-9e7b-412f-9797-7a017340a4f4
		summarizeBy: none
		sourceColumn: Suburb

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 6f06903d-4e4f-4432-9ec6-1de0bd61bd94
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column PostCode
		dataType: string
		lineageTag: 21aea846-fb1b-4193-94e8-18b3c21451ea
		summarizeBy: none
		sourceColumn: PostCode

		annotation SummarizationSetBy = Automatic

	column Longitude
		dataType: string
		lineageTag: 7b86fd20-8a18-4425-abfb-96aae564b2a9
		summarizeBy: none
		sourceColumn: Longitude

		annotation SummarizationSetBy = Automatic

	column Latitude
		dataType: string
		lineageTag: d02bdacf-4478-4ddb-9309-e47d15ff01b2
		summarizeBy: none
		sourceColumn: Latitude

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: 8b9dcfb1-8733-4114-af7b-afc55d451608
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column Phone1
		dataType: string
		lineageTag: d601e340-377c-47ae-8504-c715791f55da
		summarizeBy: none
		sourceColumn: Phone1

		annotation SummarizationSetBy = Automatic

	column Phone2
		dataType: string
		lineageTag: 52139fc0-6fca-43ff-a5b0-44eb927b84f5
		summarizeBy: none
		sourceColumn: Phone2

		annotation SummarizationSetBy = Automatic

	column PhoneSMS
		dataType: string
		lineageTag: db47cefe-cd34-4b5b-bed0-947fda7235b9
		summarizeBy: none
		sourceColumn: PhoneSMS

		annotation SummarizationSetBy = Automatic

	column Fax
		dataType: string
		lineageTag: 5bdc81c9-08f2-492f-955d-1a72ce96c9bc
		summarizeBy: none
		sourceColumn: Fax

		annotation SummarizationSetBy = Automatic

	column ContactPref
		dataType: string
		lineageTag: 9abb8b4f-18dd-41b0-a6eb-44db8fa1156b
		summarizeBy: none
		sourceColumn: ContactPref

		annotation SummarizationSetBy = Automatic

	column DateOfBirth
		dataType: string
		lineageTag: 00eda301-396b-4f4a-885f-f976381b943f
		summarizeBy: none
		sourceColumn: DateOfBirth

		annotation SummarizationSetBy = Automatic

	column PayerId
		dataType: string
		lineageTag: e713cdeb-7315-4dba-b03d-cad293f443b7
		summarizeBy: none
		sourceColumn: PayerId

		annotation SummarizationSetBy = Automatic

	column Area
		dataType: string
		lineageTag: 88d36d79-9c22-4f5c-bcb1-00d92cfa731f
		summarizeBy: none
		sourceColumn: Area

		annotation SummarizationSetBy = Automatic

	column Division
		dataType: string
		lineageTag: 8ae4a695-7614-4bd5-a218-2deb88080518
		summarizeBy: none
		sourceColumn: Division

		annotation SummarizationSetBy = Automatic

	column Group
		dataType: string
		lineageTag: 62e884d0-1ff6-4c75-bd6b-7f3a56e6cccd
		summarizeBy: none
		sourceColumn: Group

		annotation SummarizationSetBy = Automatic

	column CaseManager
		dataType: string
		lineageTag: 67259f31-47c9-4cb7-85e1-7ee7e08a1baa
		summarizeBy: none
		sourceColumn: CaseManager

		annotation SummarizationSetBy = Automatic

	column CaseManager2
		dataType: string
		lineageTag: 086c4292-6fe0-4fec-9f45-ae905875680d
		summarizeBy: none
		sourceColumn: CaseManager2

		annotation SummarizationSetBy = Automatic

	column MaritalStatus
		dataType: string
		lineageTag: 310e936f-f748-46b0-ba88-67757b9223a5
		summarizeBy: none
		sourceColumn: MaritalStatus

		annotation SummarizationSetBy = Automatic

	column Aboriginal
		dataType: string
		lineageTag: 3c29237c-2740-45d7-9e1b-a19634b6cb96
		summarizeBy: none
		sourceColumn: Aboriginal

		annotation SummarizationSetBy = Automatic

	column TorresStraitIslander
		dataType: string
		lineageTag: e154c4d3-50c6-47d7-911b-189443075139
		summarizeBy: none
		sourceColumn: TorresStraitIslander

		annotation SummarizationSetBy = Automatic

	column LGBQTI
		dataType: string
		lineageTag: d9c539a4-329d-448e-a176-2ec40c1df8b5
		summarizeBy: none
		sourceColumn: LGBQTI

		annotation SummarizationSetBy = Automatic

	column LanguageEnglish
		dataType: string
		lineageTag: 98bc5a0d-1921-4fae-8363-b85b903c64ce
		summarizeBy: none
		sourceColumn: LanguageEnglish

		annotation SummarizationSetBy = Automatic

	column LanguageOther
		dataType: string
		lineageTag: 10b8bd8b-f7a0-4f84-b5f6-6c11ed45cc53
		summarizeBy: none
		sourceColumn: LanguageOther

		annotation SummarizationSetBy = Automatic

	column InterpreterRequired
		dataType: string
		lineageTag: c17943dd-2b96-42db-9342-43e290121e25
		summarizeBy: none
		sourceColumn: InterpreterRequired

		annotation SummarizationSetBy = Automatic

	column ClientNo
		dataType: string
		lineageTag: f1769472-bfcb-4b56-93f1-ed66f3e699c1
		summarizeBy: none
		sourceColumn: ClientNo

		annotation SummarizationSetBy = Automatic

	column AccountingCode
		dataType: string
		lineageTag: 04243a2e-8b98-4daf-8677-61af68711351
		summarizeBy: none
		sourceColumn: AccountingCode

		annotation SummarizationSetBy = Automatic

	column MedicareNo
		dataType: string
		lineageTag: bf4c6e4a-1a71-403c-b43d-d76154bf2859
		summarizeBy: none
		sourceColumn: MedicareNo

		annotation SummarizationSetBy = Automatic

	column AmbulanceNo
		dataType: string
		lineageTag: d0eadf93-4db3-45d6-9f99-febe2cf016e0
		summarizeBy: none
		sourceColumn: AmbulanceNo

		annotation SummarizationSetBy = Automatic

	column Weight
		dataType: string
		lineageTag: e9ae3760-dcbf-4665-8b41-959c065d582c
		summarizeBy: none
		sourceColumn: Weight

		annotation SummarizationSetBy = Automatic

	column Height
		dataType: string
		lineageTag: a65eb4ee-a243-48b4-b5dc-f82cb5d89a02
		summarizeBy: none
		sourceColumn: Height

		annotation SummarizationSetBy = Automatic

	column DVA
		dataType: string
		lineageTag: 07f6e3dc-176a-4639-9b14-d880f4e86c1f
		summarizeBy: none
		sourceColumn: DVA

		annotation SummarizationSetBy = Automatic

	column TSI
		dataType: string
		lineageTag: b993f88e-ea04-41a9-802e-27f45380ac3a
		summarizeBy: none
		sourceColumn: TSI

		annotation SummarizationSetBy = Automatic

	column ATSI
		dataType: string
		lineageTag: ad55e3a8-9ef9-4d59-b41c-491f401f4be4
		summarizeBy: none
		sourceColumn: ATSI

		annotation SummarizationSetBy = Automatic

	column CALD
		dataType: string
		lineageTag: 27ed8796-e8cc-4ff4-8851-975a341fda4b
		summarizeBy: none
		sourceColumn: CALD

		annotation SummarizationSetBy = Automatic

	column CHSP
		dataType: string
		lineageTag: 2b62b0b2-2f44-421c-b7e9-706aa51f9e12
		summarizeBy: none
		sourceColumn: CHSP

		annotation SummarizationSetBy = Automatic

	column SATSS
		dataType: string
		lineageTag: cf8e311a-99a7-45ad-8907-6036978aa6ee
		summarizeBy: none
		sourceColumn: SATSS

		annotation SummarizationSetBy = Automatic

	column HCPLevel
		dataType: string
		lineageTag: 2edf66a0-65aa-41d1-b415-7e4cc59700b9
		summarizeBy: none
		sourceColumn: HCPLevel

		annotation SummarizationSetBy = Automatic

	column LiveAlone
		dataType: string
		lineageTag: b6ebfdcd-968c-49d6-8d2d-a6940a665cb7
		summarizeBy: none
		sourceColumn: LiveAlone

		annotation SummarizationSetBy = Automatic

	column SingleWorker
		dataType: string
		lineageTag: fcc13868-ff83-4895-a576-eb4679415b20
		summarizeBy: none
		sourceColumn: SingleWorker

		annotation SummarizationSetBy = Automatic

	column CompanionCard
		dataType: string
		lineageTag: 80cfc586-b590-4468-923c-e8b3a4d84493
		summarizeBy: none
		sourceColumn: CompanionCard

		annotation SummarizationSetBy = Automatic

	column PrivateHealth
		dataType: string
		lineageTag: bd2af3b5-1b93-4167-9905-4e6da00f42c9
		summarizeBy: none
		sourceColumn: PrivateHealth

		annotation SummarizationSetBy = Automatic

	column LegalOrders
		dataType: string
		lineageTag: b087c530-7501-4997-935f-3061cac9fe52
		summarizeBy: none
		sourceColumn: LegalOrders

		annotation SummarizationSetBy = Automatic

	column LivingArrangement
		dataType: string
		lineageTag: a5985b6b-8f4d-4fbc-9580-ed4fdb23c3b9
		summarizeBy: none
		sourceColumn: LivingArrangement

		annotation SummarizationSetBy = Automatic

	column EmploymentType
		dataType: string
		lineageTag: 22b1dd71-a9e5-4d6d-9ba4-3f5e00627b64
		summarizeBy: none
		sourceColumn: EmploymentType

		annotation SummarizationSetBy = Automatic

	column Referral
		dataType: string
		lineageTag: f16f0a82-8422-46ea-a9ee-0bf053f4c3a0
		summarizeBy: none
		sourceColumn: Referral

		annotation SummarizationSetBy = Automatic

	column Referer
		dataType: string
		lineageTag: 50ceb8e4-1612-451d-b604-26f02196b38f
		summarizeBy: none
		sourceColumn: Referer

		annotation SummarizationSetBy = Automatic

	column RefererCode
		dataType: string
		lineageTag: 0d0c25a4-9999-4958-b8b5-9213fccdea0f
		summarizeBy: none
		sourceColumn: RefererCode

		annotation SummarizationSetBy = Automatic

	column MACCode
		dataType: string
		lineageTag: 20405333-05c0-483d-b49e-54f0f707e8cf
		summarizeBy: none
		sourceColumn: MACCode

		annotation SummarizationSetBy = Automatic

	column MyAgedCareReference
		dataType: string
		lineageTag: ffc720c7-95ea-4fcb-9e75-1e77b79eba79
		summarizeBy: none
		sourceColumn: MyAgedCareReference

		annotation SummarizationSetBy = Automatic

	column NotesAccess
		dataType: string
		lineageTag: 4a680bd4-3c73-4a35-a42f-821f131784eb
		summarizeBy: none
		sourceColumn: NotesAccess

		annotation SummarizationSetBy = Automatic

	column NotesRisk
		dataType: string
		lineageTag: e2bf78cc-b244-4317-a60e-a5dad0ccaf0c
		summarizeBy: none
		sourceColumn: NotesRisk

		annotation SummarizationSetBy = Automatic

	column NotesAlert
		dataType: string
		lineageTag: dc84cc08-beaa-41aa-8866-41aa559cfeef
		summarizeBy: none
		sourceColumn: NotesAlert

		annotation SummarizationSetBy = Automatic

	column NotesGeneral
		dataType: string
		lineageTag: 324bc773-9125-45d3-b4ee-7d0d8f7fcbcb
		summarizeBy: none
		sourceColumn: NotesGeneral

		annotation SummarizationSetBy = Automatic

	column NotesRoster
		dataType: string
		lineageTag: c44bb6fb-b765-4960-af24-b8c0fcd0d4f1
		summarizeBy: none
		sourceColumn: NotesRoster

		annotation SummarizationSetBy = Automatic

	column NotesClientProfile
		dataType: string
		lineageTag: 479033b8-bf9e-46f9-a98b-83553b4fe412
		summarizeBy: none
		sourceColumn: NotesClientProfile

		annotation SummarizationSetBy = Automatic

	column NotesShiftAlert
		dataType: string
		lineageTag: 1335d818-62c0-4112-b1bb-3d355457b998
		summarizeBy: none
		sourceColumn: NotesShiftAlert

		annotation SummarizationSetBy = Automatic

	column CurrentStatus
		dataType: string
		lineageTag: 1adb5bb8-2c1e-48e6-8f5a-4df417cfac4a
		summarizeBy: none
		sourceColumn: CurrentStatus

		annotation SummarizationSetBy = Automatic

	column ServiceStatus
		dataType: string
		lineageTag: 12168cbe-3ca2-4529-a02d-e1ddd669653a
		summarizeBy: none
		sourceColumn: ServiceStatus

		annotation SummarizationSetBy = Automatic

	column ServiceStart
		dataType: string
		lineageTag: 2731229c-7600-4d53-b5bb-d221cb27dd88
		summarizeBy: none
		sourceColumn: ServiceStart

		annotation SummarizationSetBy = Automatic

	column ServiceEnd
		dataType: string
		lineageTag: 8ff71e7a-0dfc-4d63-9190-b0dadbd7683c
		summarizeBy: none
		sourceColumn: ServiceEnd

		annotation SummarizationSetBy = Automatic

	column ServiceReview
		dataType: string
		lineageTag: eb374f00-0d92-4ff5-9c85-56e5076607fd
		summarizeBy: none
		sourceColumn: ServiceReview

		annotation SummarizationSetBy = Automatic

	column ServiceReview2
		dataType: string
		lineageTag: fca308d2-6744-4d3a-93fb-85fb097e52e8
		summarizeBy: none
		sourceColumn: ServiceReview2

		annotation SummarizationSetBy = Automatic

	column EnquiryDate
		dataType: string
		lineageTag: 40b9315c-1d81-43b7-bbe2-2dd91545e8ca
		summarizeBy: none
		sourceColumn: EnquiryDate

		annotation SummarizationSetBy = Automatic

	column LastServiceReview
		dataType: string
		lineageTag: 29e3f17e-5943-4cca-ba24-4e1e81c48d5d
		summarizeBy: none
		sourceColumn: LastServiceReview

		annotation SummarizationSetBy = Automatic

	column ReasonServiceEnded
		dataType: string
		lineageTag: e2a6d116-5f02-4b40-b578-83600c59fe89
		summarizeBy: none
		sourceColumn: ReasonServiceEnded

		annotation SummarizationSetBy = Automatic

	column NIDISNo
		dataType: string
		lineageTag: 7cf2ee56-0743-4ed3-ae26-9f7c7f29eb51
		summarizeBy: none
		sourceColumn: NIDISNo

		annotation SummarizationSetBy = Automatic

	column NDISNumber
		dataType: string
		lineageTag: 44644862-0591-4d53-8892-ccc6083eb1c3
		summarizeBy: none
		sourceColumn: NDISNumber

		annotation SummarizationSetBy = Automatic

	column NDISNote
		dataType: string
		lineageTag: 5898a20a-e3a0-4ccb-bb89-f87c755422d4
		summarizeBy: none
		sourceColumn: NDISNote

		annotation SummarizationSetBy = Automatic

	column PensionNo
		dataType: string
		lineageTag: 0bad6433-0347-4abd-aa9b-7de48e092973
		summarizeBy: none
		sourceColumn: PensionNo

		annotation SummarizationSetBy = Automatic

	column CareRecipientId
		dataType: string
		lineageTag: 63429944-7d08-48f8-a0d6-8a889322f78c
		summarizeBy: none
		sourceColumn: CareRecipientId

		annotation SummarizationSetBy = Automatic

	column IsDex
		dataType: string
		lineageTag: b644e9ad-9fce-4c2c-840e-2f9c7f184d81
		summarizeBy: none
		sourceColumn: IsDex

		annotation SummarizationSetBy = Automatic

	column DexClientId
		dataType: string
		lineageTag: db34a20e-495d-433d-9d67-99913b3bed11
		summarizeBy: none
		sourceColumn: DexClientId

		annotation SummarizationSetBy = Automatic

	column Slk
		dataType: string
		lineageTag: a8e45766-ad4f-4915-8447-7e116669ef40
		summarizeBy: none
		sourceColumn: Slk

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: f4b13452-e513-4431-a2cf-96625177e827
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column LocationId
		dataType: string
		lineageTag: c7e160b3-c389-4cfb-9b4f-57927c5f08dd
		summarizeBy: none
		sourceColumn: LocationId

		annotation SummarizationSetBy = Automatic

	column Current
		dataType: string
		lineageTag: 4139f171-fd2a-47b2-bf00-bae863868077
		summarizeBy: none
		sourceColumn: Current

		annotation SummarizationSetBy = Automatic

	column CreatedBy
		dataType: string
		lineageTag: 54edc788-4559-4a77-8ac6-c16808064299
		summarizeBy: none
		sourceColumn: CreatedBy

		annotation SummarizationSetBy = Automatic

	column CreatedTime
		dataType: string
		lineageTag: 8b551844-3969-44ce-971a-346de0c2ee46
		summarizeBy: none
		sourceColumn: CreatedTime

		annotation SummarizationSetBy = Automatic

	column LastModifiedTime
		dataType: string
		lineageTag: 3b2fa209-6c1f-4776-b583-42ed56f78912
		summarizeBy: none
		sourceColumn: LastModifiedTime

		annotation SummarizationSetBy = Automatic

	column PreferedWorker
		dataType: string
		lineageTag: bc1b2dca-341b-480a-9500-dd4ad3e30f44
		summarizeBy: none
		sourceColumn: PreferedWorker

		annotation SummarizationSetBy = Automatic

	column NonPreferedWorker
		dataType: string
		lineageTag: edf0ab8f-fe6a-4def-bc0e-2167bf0d9131
		summarizeBy: none
		sourceColumn: NonPreferedWorker

		annotation SummarizationSetBy = Automatic

	partition 'Dim FSP Clients' = m
		mode: import
		queryGroup: Clients
		source =
				let
				    Source = #"Clients - Source",
				    #"Filtered Rows1" = Table.SelectRows(Source, each Text.Contains([LastName], "FSP") or Text.Contains([FirstName], "FSP") or Text.Contains([Group], "22"))
				in
				    #"Filtered Rows1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

