table DimRosterServicesVisualCare
	lineageTag: e980bca3-4ca3-4278-af2a-3eb3d91c55db

	column ServiceId
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ac842350-8035-4a81-b70a-6372cd029a50
		summarizeBy: none
		sourceColumn: ServiceId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ServiceCode
		dataType: string
		lineageTag: 7cc051de-a0f4-4c78-9464-05ae29fc777b
		summarizeBy: none
		sourceColumn: ServiceCode

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: dadb4ec9-a5e2-4555-aa61-9b113a3b1cec
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column Unit
		dataType: string
		lineageTag: d5aea62f-1fb4-477d-8f0e-a81277f370b6
		summarizeBy: none
		sourceColumn: Unit

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 11f45a7b-a474-4929-90ff-7bfb12a3b7d6
		summarizeBy: none
		sourceColumn: Category

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ExpenseCategory
		dataType: int64
		formatString: 0
		lineageTag: aaa86292-c5bb-4867-890d-36d7c613f091
		summarizeBy: sum
		sourceColumn: ExpenseCategory

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: 5ea64f8f-5884-4bed-893d-d926f4a1381f
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column ShiftType
		dataType: string
		lineageTag: 86381945-a4af-4993-b141-fe0a7925ec66
		summarizeBy: none
		sourceColumn: ShiftType

		annotation SummarizationSetBy = Automatic

	column IsSleepover
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 3ae2d73c-8937-4f25-be60-5fe575b4e714
		summarizeBy: none
		sourceColumn: IsSleepover

		annotation SummarizationSetBy = Automatic

	column IsNormalTime
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 62169f22-b59c-4a37-a4e7-da599d2746ac
		summarizeBy: none
		sourceColumn: IsNormalTime

		annotation SummarizationSetBy = Automatic

	column LinkedNormalTime
		dataType: int64
		formatString: 0
		lineageTag: 9d1b8185-ac7d-4b7f-ad01-ec5561c59e84
		summarizeBy: sum
		sourceColumn: LinkedNormalTime

		annotation SummarizationSetBy = Automatic

	column ChargeRate
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: f9ecf5ab-7ef9-4303-9345-19aed140b76e
		summarizeBy: sum
		sourceColumn: ChargeRate

		annotation SummarizationSetBy = Automatic

	column ChargeRate2
		dataType: double
		lineageTag: 37fc20fe-9cd1-4753-9640-183cd0cdf19c
		summarizeBy: sum
		sourceColumn: ChargeRate2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ChargeRate3
		dataType: double
		lineageTag: f8491022-c8a9-4f03-93c9-93145fee25ee
		summarizeBy: sum
		sourceColumn: ChargeRate3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CHSPRate
		dataType: double
		lineageTag: 4e9973b0-ef90-442b-9d64-df82a11d35fb
		summarizeBy: sum
		sourceColumn: CHSPRate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AccountingCode
		dataType: string
		lineageTag: 4b5cb7b8-753c-4164-951d-6aa5f19d19af
		summarizeBy: none
		sourceColumn: AccountingCode

		annotation SummarizationSetBy = Automatic

	column GST
		dataType: double
		lineageTag: dd1bd739-de1d-4d0c-ab81-9b175a4ef3d1
		summarizeBy: sum
		sourceColumn: GST

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NDISSupportNumber
		dataType: string
		lineageTag: 0a1526de-eaf8-4e7f-b841-119edb52e85a
		summarizeBy: none
		sourceColumn: NDISSupportNumber

		annotation SummarizationSetBy = Automatic

	column NDISGSTCode
		dataType: string
		lineageTag: 0a6edfa6-4525-4b20-89b4-84b3c665f6fc
		summarizeBy: none
		sourceColumn: NDISGSTCode

		annotation SummarizationSetBy = Automatic

	column NDISRegGrpNumber
		dataType: double
		lineageTag: ee0863a9-cbae-4544-b0c5-27479a64a363
		summarizeBy: sum
		sourceColumn: NDISRegGrpNumber

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NDISKmCode
		dataType: int64
		formatString: 0
		lineageTag: e8fc10b7-a271-45be-8fec-966743ab0a15
		summarizeBy: count
		sourceColumn: NDISKmCode

		annotation SummarizationSetBy = Automatic

	column NDISCentreCapitalCosts
		dataType: int64
		formatString: 0
		lineageTag: 54e29508-ffcd-48d7-bb85-61936facf7c8
		summarizeBy: sum
		sourceColumn: NDISCentreCapitalCosts

		annotation SummarizationSetBy = Automatic

	column HACCItemNumber
		dataType: double
		lineageTag: 46143ffd-fbf9-4f4e-9649-b3bf5e8d434f
		summarizeBy: sum
		sourceColumn: HACCItemNumber

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column _LastModTime
		dataType: dateTime
		formatString: General Date
		lineageTag: 9c0e7eae-62d9-4e53-8df4-1c31644ce6df
		summarizeBy: none
		sourceColumn: _LastModTime

		variation Variation
			isDefault
			relationship: ba0f1eaf-8da4-4343-bd07-d4b3b0bd65d1
			defaultHierarchy: LocalDateTable_2a04bb1a-298a-4a5c-9bfc-628c13478497.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column _LastModUser
		dataType: string
		lineageTag: d9e9ec94-c37b-451b-8aaa-e947b14a0f9a
		summarizeBy: none
		sourceColumn: _LastModUser

		annotation SummarizationSetBy = Automatic

	column _CreateTime
		dataType: dateTime
		formatString: General Date
		lineageTag: d451226c-7a65-4d09-8c70-969bd0953f1a
		summarizeBy: none
		sourceColumn: _CreateTime

		variation Variation
			isDefault
			relationship: e1db2395-a7cf-4e7d-ab5c-97606411d45f
			defaultHierarchy: LocalDateTable_b55d080e-15bd-4388-b1c9-ff08a468422d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column _CreateUser
		dataType: string
		lineageTag: e02599a1-555a-48ca-89d7-a4f3ba6d1804
		summarizeBy: none
		sourceColumn: _CreateUser

		annotation SummarizationSetBy = Automatic

	column Active
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 6396d544-6513-47f0-b98b-089603357d07
		summarizeBy: none
		sourceColumn: Active

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: deb27204-3f25-4fbf-97ff-636ae2227ac1
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column CYFServiceFundingType
		dataType: string
		lineageTag: 504dd027-90fe-4012-a4b2-eeb4228c1386
		summarizeBy: none
		sourceColumn: CYFServiceFundingType

		annotation SummarizationSetBy = Automatic

	column BillableUnitsMultiplier
		dataType: double
		lineageTag: 8f2cfe84-d150-431f-a5e2-a791ef37f774
		summarizeBy: sum
		sourceColumn: BillableUnitsMultiplier

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition DimRosterServicesVisualCare = m
		mode: import
		queryGroup: Services
		source =
				let
				    Source = #"Services - source",
				    #"Added Conditional Column" = Table.AddColumn(Source, "CYFServiceFundingType", each if Text.Contains([ServiceCode], "CS-G") then "OSD" else if Text.Contains([ServiceCode], "CS-F") then "IPS" else if Text.Contains([ServiceCode], "CS-C") then "IPS" else if Text.Contains([ServiceCode], "CS-S") then "IPS" else "Other"),
				    #"Added Conditional Column1" = Table.AddColumn(#"Added Conditional Column", "BillableUnitsMultiplier", each if Text.Contains([ServiceCode], "1:2") then 1/2 else if Text.Contains([ServiceCode], "1:3") then 1/3 else if Text.Contains([ServiceCode], "1:4") then 1/4 else 1),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Conditional Column1",{{"BillableUnitsMultiplier", type number}, {"CYFServiceFundingType", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

