table DimServiceCategories
	lineageTag: 6969e04b-f478-41b1-927b-bd06ac33b71b

	column CategoryId
		dataType: int64
		formatString: 0
		lineageTag: 46805795-e271-4475-a003-bcee4e4b27d1
		summarizeBy: none
		sourceColumn: CategoryId

		annotation SummarizationSetBy = Automatic

	column CategoryCode
		dataType: string
		lineageTag: 6f8076aa-dc3b-4500-b812-a67e404dea52
		summarizeBy: none
		sourceColumn: CategoryCode

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: cb7cf415-8f05-48d1-9fca-15959c12640f
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	partition DimServiceCategories = m
		mode: import
		queryGroup: Services
		source =
				let
				    Source = Json.Document(Web.Contents("https://publicapi.visualcare.com.au/category-services", [Query=[includeDeleted="TRUE"],Headers=[User=VisualCareUser, Key=VisualCareKey, Secret=VisualCareSecret]])),
				    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"CategoryId", "CategoryCode", "Description"}, {"CategoryId", "CategoryCode", "Description"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Column1",{{"CategoryId", Int64.Type}, {"CategoryCode", type text}, {"Description", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

