table DimWorkforceVisualCare
	lineageTag: 2313501e-dd05-46fe-9b3b-7cca3c5fb12b

	column CarerId
		dataType: int64
		formatString: 0
		lineageTag: b5b94480-553a-4cf0-b07f-c1b1e8bcfaf4
		summarizeBy: none
		sourceColumn: CarerId

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: b2d902ff-25b9-44cc-b4fd-a09f6e094365
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: f20ecaff-9da6-4f1f-b17d-e40a2ec368ff
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column PreferredName
		dataType: string
		lineageTag: f1ef519a-3ecb-4146-be53-4d2b634dd0fa
		summarizeBy: none
		sourceColumn: PreferredName

		annotation SummarizationSetBy = Automatic

	column Address1
		dataType: string
		lineageTag: 56c73552-28f3-4bf8-bc21-2dae83dce024
		summarizeBy: none
		sourceColumn: Address1

		annotation SummarizationSetBy = Automatic

	column Address2
		dataType: string
		lineageTag: 58336e5f-05c1-4291-841a-919090bda7c0
		summarizeBy: none
		sourceColumn: Address2

		annotation SummarizationSetBy = Automatic

	column Suburb
		dataType: string
		lineageTag: 797e18a7-f909-4116-8d3b-6c5920aa8199
		summarizeBy: none
		sourceColumn: Suburb

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 80df353f-6f4b-402b-ab00-d93101230e06
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column PostCode
		dataType: string
		lineageTag: 854c1e18-55b9-4899-a0d3-eb8f661bf0e5
		summarizeBy: none
		sourceColumn: PostCode

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: 2b83413c-b151-491c-8a57-8410902d7074
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column Phone1
		dataType: string
		lineageTag: 89d49223-f182-4d77-9aa7-cd49d5c39ca0
		summarizeBy: none
		sourceColumn: Phone1

		annotation SummarizationSetBy = Automatic

	column Phone2
		dataType: string
		lineageTag: 9f880b35-fa43-496c-aeab-e44272c70612
		summarizeBy: none
		sourceColumn: Phone2

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 8e120a72-0b76-4197-ad0f-ac3403b05046
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column Sex
		dataType: string
		lineageTag: 95041aa4-4e3d-4b2d-b28a-426ba4d76246
		summarizeBy: none
		sourceColumn: Sex

		annotation SummarizationSetBy = Automatic

	column Marital
		dataType: string
		lineageTag: 92e6b4fb-8daf-4c51-a047-9f94d5777383
		summarizeBy: none
		sourceColumn: Marital

		annotation SummarizationSetBy = Automatic

	column Smoker
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 146baa35-6203-4597-a853-3986e975abcb
		summarizeBy: none
		sourceColumn: Smoker

		annotation SummarizationSetBy = Automatic

	column PetFriendly
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e2a921f7-ad05-4057-b6f7-49d561283f78
		summarizeBy: none
		sourceColumn: PetFriendly

		annotation SummarizationSetBy = Automatic

	column WorkWithChildren
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e195664b-addb-4595-9dbf-01ab8e35181b
		summarizeBy: none
		sourceColumn: WorkWithChildren

		annotation SummarizationSetBy = Automatic

	column Division
		dataType: string
		lineageTag: edecc673-57b2-4df4-a863-1049086a6f05
		summarizeBy: none
		sourceColumn: Division

		annotation SummarizationSetBy = Automatic

	column CaseManager
		dataType: string
		lineageTag: b705ff78-36bb-4650-9cd7-0af517ee52c1
		summarizeBy: none
		sourceColumn: CaseManager

		annotation SummarizationSetBy = Automatic

	column WorkerType
		dataType: string
		lineageTag: e807b7f9-ad7c-4097-9ed9-e810fa91ef50
		summarizeBy: none
		sourceColumn: WorkerType

		annotation SummarizationSetBy = Automatic

	column AwardSector
		dataType: string
		lineageTag: 240d5961-150b-4c88-8479-cf645bb89621
		summarizeBy: none
		sourceColumn: AwardSector

		annotation SummarizationSetBy = Automatic

	column InIsolation
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: eecc51ed-3fd3-46f7-a208-852f07b14f1a
		summarizeBy: none
		sourceColumn: InIsolation

		annotation SummarizationSetBy = Automatic

	column CovidVaccine1
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c0fe8e45-9ddf-447e-8f09-baa46f65ba98
		summarizeBy: none
		sourceColumn: CovidVaccine1

		annotation SummarizationSetBy = Automatic

	column CovidVaccine2
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: a356aab5-f657-4d59-b35f-1c770496da21
		summarizeBy: none
		sourceColumn: CovidVaccine2

		annotation SummarizationSetBy = Automatic

	column WebEnabled
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 2a5f282d-cef2-4b91-bc33-48633b1bd924
		summarizeBy: none
		sourceColumn: WebEnabled

		annotation SummarizationSetBy = Automatic

	column CarerStatus
		dataType: string
		lineageTag: 8a2cbe1d-2e3b-460a-89f2-69eaa6f2d47e
		summarizeBy: none
		sourceColumn: CarerStatus

		annotation SummarizationSetBy = Automatic

	column ResignReason
		dataType: string
		lineageTag: b2472bff-1c5b-4a66-81da-3c60e9098bf0
		summarizeBy: none
		sourceColumn: ResignReason

		annotation SummarizationSetBy = Automatic

	column NDISClearance
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 6baf8c1c-4f04-420b-a48b-b86330f3a0cd
		summarizeBy: none
		sourceColumn: NDISClearance

		annotation SummarizationSetBy = Automatic

	column Current
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 18e03ff6-44ab-4e12-8875-eefeed493ac2
		summarizeBy: none
		sourceColumn: Current

		annotation SummarizationSetBy = Automatic

	column RoleDescription
		dataType: string
		lineageTag: 11f7a331-4b28-47d1-8cbc-106ca699664b
		summarizeBy: none
		sourceColumn: RoleDescription

		annotation SummarizationSetBy = Automatic

	column AwardDesc
		dataType: string
		lineageTag: ae63d8a4-e7f3-45d2-874b-de395deaf31a
		summarizeBy: none
		sourceColumn: AwardDesc

		annotation SummarizationSetBy = Automatic

	column FullName
		dataType: string
		lineageTag: 0d94b12e-f511-40c8-8c05-712353796d40
		summarizeBy: none
		sourceColumn: FullName

		annotation SummarizationSetBy = Automatic

	column Area
		dataType: string
		lineageTag: 206023fc-83a6-4c34-9786-a279b84fa7d8
		summarizeBy: none
		sourceColumn: Area

		annotation SummarizationSetBy = Automatic

	partition DimWorkforceVisualCare = m
		mode: import
		queryGroup: Workers
		source =
				let
				    Source = #"Current workers - source",
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"CarerId", "FirstName", "LastName", "PreferredName", "Address1", "Address2", "Suburb", "State", "PostCode", "Email", "Phone1", "Phone2", "Description", "Sex", "Marital", "Smoker", "PetFriendly", "WorkWithChildren", "Area", "Division", "CaseManager", "WorkerType", "AwardSector", "InIsolation", "CovidVaccine1", "CovidVaccine2", "WebEnabled", "CarerStatus", "ResignReason", "NDISClearance", "Current", "RoleDescription", "AwardDesc"}),
				    #"Added Custom" = Table.AddColumn(#"Removed Other Columns", "FullName", each [FirstName] & " " & [LastName]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom",{{"FullName", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

