table DimClientServiceStartDate
	lineageTag: 2ed7e9ca-3b92-4a93-9dae-35133f4a31e0

	column ServiceStartDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 23575437-07fa-4f63-a350-869f9d7ae9bb
		summarizeBy: none
		sourceColumn: ServiceStartDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 9c5d7f71-1d82-4242-89b1-9bfe054ffba0
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 77dd4bb1-3f06-4aa2-9a45-bdc0e8ccae94
		summarizeBy: none
		sourceColumn: MonthName

		annotation SummarizationSetBy = Automatic

	column 'MMM YYYY'
		dataType: string
		lineageTag: fdb018c0-e3b9-4537-85b7-e94f57c76655
		summarizeBy: none
		sourceColumn: MMM YYYY
		sortByColumn: YYYYMM

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column MonthNumber
		dataType: int64
		formatString: 0
		lineageTag: 7c8a4d3d-e462-434f-9bc8-c8b55412c997
		summarizeBy: none
		sourceColumn: MonthNumber

		annotation SummarizationSetBy = Automatic

	column 'Start of Month'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5740455e-bcf5-4f79-88d2-45b0a4101a6f
		summarizeBy: none
		sourceColumn: Start of Month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column YYYYMM
		dataType: string
		isHidden
		lineageTag: 4e9a3702-a338-42ce-95f4-a41a7ead7ba0
		summarizeBy: none
		sourceColumn: YYYYMM

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DayNumber
		dataType: int64
		formatString: 0
		lineageTag: f11305e3-7f9c-4827-8866-19d970f0a11a
		summarizeBy: none
		sourceColumn: DayNumber

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: d5de1cbe-8590-4e4c-92ae-87766ad81565
		summarizeBy: none
		sourceColumn: DayName

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		formatString: 0
		lineageTag: 0411f98a-dd65-4dad-9197-1d7799f5b144
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column StartOfWeek
		dataType: dateTime
		formatString: Short Date
		lineageTag: 89e58827-e398-46ff-a66b-1b8f7d4c6e3a
		summarizeBy: none
		sourceColumn: StartOfWeek

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column StartOfYear
		dataType: dateTime
		formatString: Long Date
		lineageTag: d4235428-d84a-4f20-b4b9-2ea844c55b3f
		summarizeBy: none
		sourceColumn: StartOfYear

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column WeekOfYear
		dataType: int64
		formatString: 0
		lineageTag: 276dbcd4-9ac3-47b7-9d9f-05e1f9d943f4
		summarizeBy: none
		sourceColumn: WeekOfYear

		annotation SummarizationSetBy = Automatic

	column WeekOfMonth
		dataType: int64
		formatString: 0
		lineageTag: 8888488a-f748-40f0-b3ba-469fd6b6c1c4
		summarizeBy: none
		sourceColumn: WeekOfMonth

		annotation SummarizationSetBy = Automatic

	column RollingDateDifference
		dataType: int64
		formatString: 0
		lineageTag: a39bc9a0-0b1a-44a8-86dd-5b4e14bc8edc
		summarizeBy: none
		sourceColumn: RollingDateDifference

		annotation SummarizationSetBy = Automatic

	column 'Slicer MMM YYYY'
		dataType: string
		lineageTag: 2613d9e9-21ca-449b-b815-5385c03891cb
		summarizeBy: none
		sourceColumn: Slicer MMM YYYY

		annotation SummarizationSetBy = Automatic

	column FortnightOfYear
		dataType: int64
		formatString: 0
		lineageTag: a484ad14-e140-4fb8-812e-d356f075f854
		summarizeBy: none
		sourceColumn: FortnightOfYear

		annotation SummarizationSetBy = Automatic

	column YYYYFF
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 0dbe767a-cb9d-484e-b278-5770203497a9
		summarizeBy: none
		sourceColumn: YYYYFF

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'FF (DD MMM YYYY)'
		dataType: string
		lineageTag: 6763cac9-ee12-4c33-84d1-08b902db014c
		summarizeBy: none
		sourceColumn: FF (DD MMM YYYY)
		sortByColumn: YYYYFF

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column ContinuousFortnights
		dataType: int64
		formatString: 0
		lineageTag: f2b17d23-b761-4477-9b94-6dbe1e24b029
		summarizeBy: none
		sourceColumn: ContinuousFortnights

		annotation SummarizationSetBy = Automatic

	column PublicHolidayFlag
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 07352ad4-a135-4bf9-9fb3-01e55684b9c5
		summarizeBy: none
		sourceColumn: PublicHolidayFlag

		annotation SummarizationSetBy = Automatic

	column 'Slicer StartOfWeek'
		dataType: string
		lineageTag: 0150fcda-966b-42cc-bcbb-972f554516c3
		summarizeBy: none
		sourceColumn: Slicer StartOfWeek

		annotation SummarizationSetBy = Automatic

	partition DimClientServiceStartDate = m
		mode: import
		source =
				let
				    Source = #"Short Calendar - Source",
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"Date", "ServiceStartDate"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

