table DimClientServiceEndDate
	lineageTag: 78bf13d7-f666-41be-b1fb-0aeb924d809f

	column ServiceEndDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 24a2a191-6a7d-42f9-a709-15d3a289ae00
		summarizeBy: none
		sourceColumn: ServiceEndDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 03e30fce-52c4-4301-ac74-8fd2e6e4518c
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: ff3194b9-7ed8-4c7b-a0cd-bd7f5b1a7a96
		summarizeBy: none
		sourceColumn: MonthName

		annotation SummarizationSetBy = Automatic

	column 'MMM YYYY'
		dataType: string
		lineageTag: 5142e0b7-c9c9-4b03-bc00-dbac2611d7c8
		summarizeBy: none
		sourceColumn: MMM YYYY

		annotation SummarizationSetBy = Automatic

	column MonthNumber
		dataType: int64
		formatString: 0
		lineageTag: efbc1d64-70b3-4256-bac4-fe226f686a21
		summarizeBy: none
		sourceColumn: MonthNumber

		annotation SummarizationSetBy = Automatic

	column 'Start of Month'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2393c79c-3927-479d-ad2d-45481d7be280
		summarizeBy: none
		sourceColumn: Start of Month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column YYYYMM
		dataType: string
		lineageTag: 1e1f2702-cbe8-47dc-a05b-9b172a5b9183
		summarizeBy: none
		sourceColumn: YYYYMM

		annotation SummarizationSetBy = Automatic

	column DayNumber
		dataType: int64
		formatString: 0
		lineageTag: d4dd5e0c-b1b1-45d2-9925-8fa560432def
		summarizeBy: none
		sourceColumn: DayNumber

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: bf298619-f6c5-41dc-898d-5b13ff1b1f7e
		summarizeBy: none
		sourceColumn: DayName

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		formatString: 0
		lineageTag: 0ec33f2a-95d9-467c-b907-ef2c25b3f6c3
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column StartOfWeek
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4e917d7f-a366-443a-be04-ffa5b466b614
		summarizeBy: none
		sourceColumn: StartOfWeek

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column StartOfYear
		dataType: dateTime
		formatString: Long Date
		lineageTag: c3ea53ae-402a-4595-840f-bcf44933a6b6
		summarizeBy: none
		sourceColumn: StartOfYear

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column WeekOfYear
		dataType: int64
		formatString: 0
		lineageTag: f822653d-bc99-4fae-9705-f8c27ebbce2f
		summarizeBy: none
		sourceColumn: WeekOfYear

		annotation SummarizationSetBy = Automatic

	column WeekOfMonth
		dataType: int64
		formatString: 0
		lineageTag: eb813c51-b6cc-4ac0-9927-e2828e1e55cb
		summarizeBy: none
		sourceColumn: WeekOfMonth

		annotation SummarizationSetBy = Automatic

	column RollingDateDifference
		dataType: int64
		formatString: 0
		lineageTag: 9721fc02-f32a-4e07-94a0-92b8013e1f5d
		summarizeBy: none
		sourceColumn: RollingDateDifference

		annotation SummarizationSetBy = Automatic

	column 'Slicer MMM YYYY'
		dataType: string
		lineageTag: 88001ce0-4816-4b5f-b8ce-5ca01199f136
		summarizeBy: none
		sourceColumn: Slicer MMM YYYY

		annotation SummarizationSetBy = Automatic

	column FortnightOfYear
		dataType: int64
		formatString: 0
		lineageTag: 6f4f4b98-620a-424b-9197-bf475a5038d5
		summarizeBy: none
		sourceColumn: FortnightOfYear

		annotation SummarizationSetBy = Automatic

	column YYYYFF
		dataType: int64
		formatString: 0
		lineageTag: 435ba802-2117-4596-b143-3520fd7fb27c
		summarizeBy: none
		sourceColumn: YYYYFF

		annotation SummarizationSetBy = Automatic

	column 'FF (DD MMM YYYY)'
		dataType: string
		lineageTag: 3bf34124-5c87-4d0a-8e9f-0b89af4c9e98
		summarizeBy: none
		sourceColumn: FF (DD MMM YYYY)

		annotation SummarizationSetBy = Automatic

	column ContinuousFortnights
		dataType: int64
		formatString: 0
		lineageTag: 83a9a448-66ff-4592-9583-7c5664f76a69
		summarizeBy: none
		sourceColumn: ContinuousFortnights

		annotation SummarizationSetBy = Automatic

	column PublicHolidayFlag
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: bb31ba4d-2117-41e4-8206-c48813be227c
		summarizeBy: none
		sourceColumn: PublicHolidayFlag

		annotation SummarizationSetBy = Automatic

	column 'Slicer StartOfWeek'
		dataType: string
		lineageTag: 19523c30-fa5a-4e10-840b-1461e60cefb9
		summarizeBy: none
		sourceColumn: Slicer StartOfWeek

		annotation SummarizationSetBy = Automatic

	partition DimClientServiceEndDate = m
		mode: import
		source =
				let
				    Source = #"Short Calendar - Source",
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"Date", "ServiceEndDate"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

