table DimEmploymentEndDate
	lineageTag: 4c45d8fb-59ec-419c-8cd7-01254b987f18

	column EmploymentEndDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: ab123c43-768e-49c6-8ba1-31aa146f12c8
		summarizeBy: none
		sourceColumn: EmploymentEndDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: c7be7226-8aa5-4e34-826c-9c5cfa4f8227
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 120dae93-5d6d-4333-8897-1ab901d712a9
		summarizeBy: none
		sourceColumn: MonthName

		annotation SummarizationSetBy = Automatic

	column 'MMM YYYY'
		dataType: string
		lineageTag: ee84b8c3-b992-4abb-a6c2-5a87ca0c4b18
		summarizeBy: none
		sourceColumn: MMM YYYY
		sortByColumn: YYYYMM

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column MonthNumber
		dataType: int64
		formatString: 0
		lineageTag: bd1cc403-63f0-454a-8e86-44374700eff2
		summarizeBy: none
		sourceColumn: MonthNumber

		annotation SummarizationSetBy = Automatic

	column YYYYMM
		dataType: string
		isHidden
		lineageTag: fa12d8c5-dba7-47c6-984a-0779b8977bf9
		summarizeBy: none
		sourceColumn: YYYYMM

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DayNumber
		dataType: int64
		formatString: 0
		lineageTag: b58cf194-837f-44aa-a516-95d7828b3f3a
		summarizeBy: none
		sourceColumn: DayNumber

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: b0f9f5b2-db27-4e9f-a81a-ed8a8c21a862
		summarizeBy: none
		sourceColumn: DayName

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		formatString: 0
		lineageTag: 3d89c20b-cd84-4e0d-ab6a-d9b735eb0da7
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column StartOfYear
		dataType: dateTime
		formatString: Long Date
		lineageTag: 02c148e1-a8ce-41e1-ba86-d30bc288ab2b
		summarizeBy: none
		sourceColumn: StartOfYear

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column WeekOfYear
		dataType: int64
		formatString: 0
		lineageTag: 770940c5-496a-46f4-bfde-ce998c53b698
		summarizeBy: none
		sourceColumn: WeekOfYear

		annotation SummarizationSetBy = Automatic

	column StartOfWeek
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6d4b96c3-b932-482a-acea-6d1d13277a26
		summarizeBy: none
		sourceColumn: StartOfWeek

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column WeekOfMonth
		dataType: int64
		formatString: 0
		lineageTag: 3eac61cb-6234-4c76-9105-e8e0b391a9cb
		summarizeBy: none
		sourceColumn: WeekOfMonth

		annotation SummarizationSetBy = Automatic

	column RollingDateDifference
		dataType: int64
		formatString: 0
		lineageTag: 90d6e293-43a5-4225-a897-c1f6108eacb2
		summarizeBy: none
		sourceColumn: RollingDateDifference

		annotation SummarizationSetBy = Automatic

	column 'Slicer MMM YYYY'
		dataType: string
		lineageTag: 97d17b3f-4b4e-4fb4-a853-c3f37b60bace
		summarizeBy: none
		sourceColumn: Slicer MMM YYYY
		sortByColumn: YYYYMM

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column FortnightOfYear
		dataType: int64
		formatString: 0
		lineageTag: 86186ed0-8915-4b34-932e-b075c61b71f4
		summarizeBy: none
		sourceColumn: FortnightOfYear

		annotation SummarizationSetBy = Automatic

	column YYYYFF
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b33e2d9e-8119-410c-8493-dba8d28fe85c
		summarizeBy: none
		sourceColumn: YYYYFF

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'FF (DD MMM YYYY)'
		dataType: string
		lineageTag: f8a86fb3-49fa-4ebb-8609-8a2e96ec1972
		summarizeBy: none
		sourceColumn: FF (DD MMM YYYY)
		sortByColumn: YYYYFF

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column ContinuousFortnights
		dataType: int64
		formatString: 0
		lineageTag: 7abd7d10-c2eb-498b-9f31-a65f6dfee04c
		summarizeBy: none
		sourceColumn: ContinuousFortnights

		annotation SummarizationSetBy = Automatic

	column PublicHolidayFlag
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 43544626-e710-4a86-a247-79c61573bc8f
		summarizeBy: none
		sourceColumn: PublicHolidayFlag

		annotation SummarizationSetBy = Automatic

	column 'Start of Month'
		dataType: dateTime
		formatString: Long Date
		lineageTag: be371afe-d801-4353-bb42-29f2e0711314
		summarizeBy: none
		sourceColumn: Start of Month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Slicer StartOfWeek'
		dataType: string
		lineageTag: 1dddc777-84d8-4d56-9c61-71b2b0c6c101
		summarizeBy: none
		sourceColumn: Slicer StartOfWeek

		annotation SummarizationSetBy = Automatic

	partition DimEmploymentEndDate = m
		mode: import
		source =
				let
				    Source = #"Short Calendar - Source",
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"Date", "EmploymentEndDate"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

