table 'Dim Calculation Semantic Model'
	isHidden
	lineageTag: 79f6d322-d1ed-40c3-8321-a4970ed731db

	column ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: cf2ddba7-b14d-4fd3-b28e-f6cbaa22139b
		summarizeBy: none
		sourceColumn: ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Semantic Model'
		dataType: string
		isHidden
		lineageTag: 5321e59b-4829-4d35-8409-d610f07ecbcc
		summarizeBy: none
		sourceColumn: Semantic Model

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Dim Calculation Semantic Model' = m
		mode: import
		queryGroup: 'Utilities\Data Dictionary'
		source =
				let
				    Source = #"Data Dictionary - Source",
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"ID", "Semantic Model"}),
				    #"Expanded Semantic Model" = Table.ExpandListColumn(#"Removed Other Columns", "Semantic Model")
				in
				    #"Expanded Semantic Model"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

