table 'Fact Shift'
	lineageTag: dc261a27-91c1-4de0-b35f-9edf5809287a

	measure FullShiftDurationHours = CALCULATE(SUM('Fact Shift'[TotalShiftDurationMins])/60, CROSSFILTER('Dim Shift Allocation'[ShiftID], 'Fact Shift'[ShiftId], Both))
		displayFolder: Duration
		lineageTag: 0b99c30a-7a2e-496e-a9a9-c034a20deecb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure FilledShiftHours = CALCULATE([ShiftDurationHoursWorked], 'Fact Shift'[Outcome] = "D-Confirmed Member and Client", 'Dim Client'[BillableClientFlag] = TRUE())
		formatString: #,0.00
		displayFolder: KPIs
		lineageTag: 573a028e-c9ca-4a35-94e8-eb698263bde0

	measure ShiftCancelledByClientHours = CALCULATE([ShiftDurationHoursWorked], 'Fact Shift'[Outcome] = "F-Cancelled by Client", 'Dim Client'[BillableClientFlag] = TRUE())
		displayFolder: KPIs
		lineageTag: d63b5eb3-a076-42a8-b31b-c5a2d9919624

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure UTFShiftStillNeededHours = CALCULATE([ShiftDurationHoursWorked], 'Fact Shift'[Outcome] = "G-Unable to Fill - Still Needed", 'Dim Client'[BillableClientFlag] = TRUE())
		displayFolder: KPIs
		lineageTag: 73551b33-e6d5-4638-8478-dfa2edb03fed

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ControllableOrdersHours = [AvailableOpportunityHours] + [UTFShiftNoLongerRequiredHours]
		displayFolder: KPIs
		lineageTag: 05a9e7b9-6549-4ea0-9e4a-82da8a682437

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Controllable Fill Rate' = DIVIDE([FilledShiftHours], [ControllableOrdersHours])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPIs
		lineageTag: 39c8fd3b-b9b5-4dfb-97c8-9068fefdc65e

	measure ShiftCancelledByClientRate = DIVIDE([ShiftCancelledByClientHours], [TotalOrdersHours])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPIs
		lineageTag: 7a34998e-f654-4fb0-9a63-91817c87dd79

	measure TotalOrdersHours = [ShiftCancelledByClientHours] + [ControllableOrdersHours]
		displayFolder: KPIs
		lineageTag: 0dfdd6ca-338e-47da-8cc3-7eaf1911862d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total hours paid' = SUM('Fact Shift'[PayHrsPaid1]) + SUM('Fact Shift'[PayHrsPaid2])
		displayFolder: Pay
		lineageTag: eeac71af-01bd-4a9b-8e78-73c62330686c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure UTFShiftNoLongerRequiredHours = CALCULATE([ShiftDurationHoursWorked], 'Fact Shift'[Outcome] = "H-Unable to Fill - No Longer Required", 'Dim Client'[BillableClientFlag] = TRUE())
		displayFolder: KPIs
		lineageTag: bb1027f3-cc2a-46e8-a1b1-aef037e54f15

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure AvailableOpportunityFilledRate = DIVIDE(COALESCE([FilledShiftHours], 0), [AvailableOpportunityHours])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPIs
		lineageTag: f3a607c4-ec0b-4ea5-a056-7de8e8bc12eb

	measure AvailableOpportunityHours = [FilledShiftHours] + [UTFShiftStillNeededHours]
		displayFolder: KPIs
		lineageTag: 433765f6-2925-42d1-abcd-94bb933cf4c9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure AverageDurationHours = CALCULATE(AVERAGE('Fact Shift'[ShiftWorkedDurationMins])/60, CROSSFILTER('Dim Workforce'[MemberId], 'Fact Shift'[MemberID], Both), 'Dim Client'[BillableClientFlag] = TRUE())
		displayFolder: Duration
		lineageTag: f5c2156c-7ffd-4d50-9c2c-bee0103dc3cc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure NonBillableDurationHours = CALCULATE('Fact Shift'[ShiftDurationHoursWorked], 'Dim Client'[BillableClientFlag] = FALSE())
		displayFolder: Duration
		lineageTag: 41ca1131-1083-4201-b033-d86b5d289870

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ShiftsFilledVsPaidHours = [FilledShiftHours] - [Total hours paid]
		displayFolder: KPIs
		lineageTag: 24a0a41f-124e-408e-8347-e8b381fb6b6b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure NewShiftHours = CALCULATE([ShiftDurationHoursWorked], 'Fact Shift'[Outcome] = "A-Unfilled", 'Dim Client'[BillableClientFlag] = TRUE())
		displayFolder: KPIs
		lineageTag: 9edde52a-07be-4916-bd49-660d415cd6dd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure BreakDurationHours = CALCULATE((SUM('Fact Shift'[MealBreakTime])/60), CROSSFILTER('Dim Shift Allocation'[ShiftID], 'Fact Shift'[ShiftId], Both))
		displayFolder: Duration
		lineageTag: 70a6e6ec-4d95-408a-934e-f10d862bcf4a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure FilledShiftBreakHours = CALCULATE([BreakDurationHours], 'Fact Shift'[Outcome] = "D-Confirmed Member and Client", 'Dim Client'[BillableClientFlag] = TRUE())
		displayFolder: KPIs
		lineageTag: 4b0f40cb-d0d5-4b4c-9786-c5da2df776b4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ShiftDurationHoursWorked = [FullShiftDurationHours] - [BreakDurationHours]
		displayFolder: Duration
		lineageTag: c7d6ef1e-3439-4953-b7de-0cc9e5736ac8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Legend = "Legend"
		lineageTag: e040fdcc-ac8f-4e41-b67a-1b77f931c2e7

	measure IncludedShiftDateRangePage = "Filtered date range: " & FORMAT(MIN('Fact Shift'[StartDateTime]), "DD/MM/YYYY hh:mm") & " - " & FORMAT(MAX('Fact Shift'[StartDateTime]), "DD/MM/YYYY hh:mm")
		displayFolder: DateTime
		lineageTag: 46528729-4beb-456e-990d-204addf11e15

	measure TotalPeriodTarget = ```
			[TotalDailyTarget] * IF(
			    DATEDIFF(MIN('Dim Shift Start Date'[ShiftStartDate]), MAX('Dim Shift Start Date'[ShiftStartDate]),DAY) = 0, 
			    1, 
			    DATEDIFF(MIN('Dim Shift Start Date'[ShiftStartDate]), MAX('Dim Shift Start Date'[ShiftStartDate]),DAY)
			)
			```
		formatString: #,0
		displayFolder: KPIs
		lineageTag: c7be7290-30f4-4987-889b-a4923bc8482f

	measure TotalDailyTarget = 550
		formatString: 0
		displayFolder: KPIs
		lineageTag: 8ac72565-98aa-45bf-9712-49bf29f4da95

	measure RemainderPeriodTarget = [TotalPeriodTarget] - [FilledShiftHours]
		displayFolder: KPIs
		lineageTag: 7923c894-50be-47cb-8888-fe510bc6e8ba

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ShiftTargetRemainderIndicatorArrows = ```
			
			VAR _remainderTarget = [RemainderPeriodTarget]
			VAR UpArrow = UNICHAR(9650)
			VAR DownArrow = UNICHAR(9660)
			VAR Result = SWITCH(TRUE, 
			     _remainderTarget = 0, "",
			     _remainderTarget < 0, UpArrow, 
			    DownArrow
			)
			
			RETURN Result  
			```
		displayFolder: KPIs
		lineageTag: ab72eacf-4574-44f5-b840-12e811ee5d62

	measure MaxDate = FORMAT(MAX('Fact Shift'[StartDateTime]), "DD/MM/YYYY")
		displayFolder: DateTime
		lineageTag: 03c952e1-51dc-49c1-a411-b7c7ce5ae58f

	measure SelectedDateRange = FORMAT(MIN('Fact Shift'[StartDateTime]), "DD/MM/YYYY") & " - " & FORMAT(MAX('Fact Shift'[StartDateTime]), "DD/MM/YYYY")
		displayFolder: DateTime
		lineageTag: 8fd2342b-00a6-46cf-adbe-31104c44b483

	column ShiftId
		dataType: int64
		formatString: 0
		lineageTag: bd27a3fd-3259-4061-88c4-cf975251fe33
		summarizeBy: none
		sourceColumn: ShiftId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AgencyID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 1fb60b26-066a-4c69-92c2-fbad95750aa7
		summarizeBy: count
		sourceColumn: AgencyID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ClientId
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 64cbba6b-1410-476f-84ab-d6bd13cee573
		summarizeBy: none
		sourceColumn: ClientId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MemberID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2649ba08-35a1-4d86-86d0-aa1a5b1d8509
		summarizeBy: none
		sourceColumn: MemberID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column InvoiceID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d4c98b43-44fd-41b5-a691-55751a4e7efd
		summarizeBy: count
		sourceColumn: InvoiceID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PayslipID
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Pay
		lineageTag: 26b200fc-9007-43e9-9022-bcf0f750d8aa
		summarizeBy: count
		sourceColumn: PayslipID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CampusId
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 6723d9fd-b6ba-4f0a-80f8-7347ba3e248a
		summarizeBy: count
		sourceColumn: CampusId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column StartDateTime
		dataType: dateTime
		formatString: General Date
		displayFolder: DateTime
		lineageTag: 07bd7ddf-9ee6-4a65-9f51-64ec5d97b5df
		summarizeBy: none
		sourceColumn: StartDateTime

		variation Variation
			isDefault
			relationship: 78448d39-8ac7-48b3-b65b-c6de2ac92418
			defaultHierarchy: LocalDateTable_46179633-0ad1-477f-9920-5043f86a27a5.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column FinishDateTime
		dataType: dateTime
		formatString: General Date
		displayFolder: DateTime
		lineageTag: 974da8ac-3230-43f4-91db-47a2752cf44d
		summarizeBy: none
		sourceColumn: FinishDateTime

		variation Variation
			isDefault
			relationship: 3f248edc-ea2c-461a-a4ab-8dfb8c66268e
			defaultHierarchy: LocalDateTable_6d358562-49f4-4561-9c0d-25d52b3d0984.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column StartDate
		dataType: dateTime
		formatString: Long Date
		displayFolder: DateTime
		lineageTag: 5ca52d40-ef7f-4f1f-909d-185007d1974e
		summarizeBy: none
		sourceColumn: StartDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FinishDate
		dataType: dateTime
		formatString: General Date
		displayFolder: DateTime
		lineageTag: 0efbfe03-adc8-410d-810b-4e7b6e33e3ae
		summarizeBy: none
		sourceColumn: FinishDate

		variation Variation
			isDefault
			relationship: 753a5e6c-728d-4343-9fdf-1f84f853a692
			defaultHierarchy: LocalDateTable_51b42e2b-b068-4fec-9d2c-cfbfdd4bf318.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column PayHrsPaid1
		dataType: double
		displayFolder: Pay
		lineageTag: eceefa2d-37fa-47b6-baae-7f380c0092da
		summarizeBy: sum
		sourceColumn: PayHrsPaid1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PayRate1
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Pay
		lineageTag: 0997a42f-c2ad-443f-8a5d-70b7994f5e23
		summarizeBy: sum
		sourceColumn: PayRate1

		annotation SummarizationSetBy = Automatic

	column PayAmount1
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Pay
		lineageTag: 097bab0c-8a0c-4757-a214-227261e0cb65
		summarizeBy: sum
		sourceColumn: PayAmount1

		annotation SummarizationSetBy = Automatic

	column PayHrsPaid2
		dataType: double
		displayFolder: Pay
		lineageTag: 6847142a-23ba-459b-887c-63ec727a10ee
		summarizeBy: sum
		sourceColumn: PayHrsPaid2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PayRate2
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Pay
		lineageTag: 795467c0-df4c-47cd-ace5-066cff87cd6b
		summarizeBy: sum
		sourceColumn: PayRate2

		annotation SummarizationSetBy = Automatic

	column PayAmount2
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Pay
		lineageTag: ddabc71f-9bcf-4d23-b68d-75cdba659a6a
		summarizeBy: sum
		sourceColumn: PayAmount2

		annotation SummarizationSetBy = Automatic

	column PaidMealBreakStatus
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: Flags
		lineageTag: 50e88608-747f-42d2-8eab-7b540eaa5c43
		summarizeBy: none
		sourceColumn: PaidMealBreakStatus

		annotation SummarizationSetBy = Automatic

	column OrderedBy
		dataType: string
		lineageTag: 650a9113-7a22-4352-94b3-cbf513b882a9
		summarizeBy: none
		sourceColumn: OrderedBy

		annotation SummarizationSetBy = Automatic

	column ShiftCreated
		dataType: dateTime
		formatString: General Date
		displayFolder: DateTime
		lineageTag: 0af27322-256c-4136-bf9d-2b8d934c7b81
		summarizeBy: none
		sourceColumn: ShiftCreated

		variation Variation
			isDefault
			relationship: 37d19d43-f8be-488e-b3b5-f70dd104986e
			defaultHierarchy: LocalDateTable_76290547-5444-47b2-afea-bd16e81875f7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column ShiftConfirmed
		dataType: dateTime
		formatString: General Date
		displayFolder: DateTime
		lineageTag: fd967840-2709-4750-90f5-976403309323
		summarizeBy: none
		sourceColumn: ShiftConfirmed

		variation Variation
			isDefault
			relationship: 29f4738f-86f1-402d-a766-509c5c74dd36
			defaultHierarchy: LocalDateTable_eca3aa1d-cd72-422d-8381-c2b0f5374e04.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column ShiftLastUpdated
		dataType: dateTime
		formatString: General Date
		displayFolder: DateTime
		lineageTag: 68fef919-f81e-4cf9-a120-a6d4abedb717
		summarizeBy: none
		sourceColumn: ShiftLastUpdated

		variation Variation
			isDefault
			relationship: cdfadcf8-506b-40c5-aa50-e06f1060ba9a
			defaultHierarchy: LocalDateTable_1f1293be-d717-4b02-8ca3-c93f847f7e4d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column EducationShiftFlag
		dataType: int64
		formatString: 0
		displayFolder: Flags
		lineageTag: ce0eb2de-cac3-4cde-835b-01eb406264f4
		summarizeBy: none
		sourceColumn: EducationShiftFlag

		annotation SummarizationSetBy = User

	column Outcome
		dataType: string
		lineageTag: ff7fe35b-ed47-440f-96d1-9ee50dd9ca66
		summarizeBy: none
		sourceColumn: Outcome

		annotation SummarizationSetBy = Automatic

	column ExtractDate
		dataType: dateTime
		formatString: General Date
		displayFolder: DateTime
		lineageTag: e21a0e47-0f68-42c4-a679-aacc3aa6ac0a
		summarizeBy: none
		sourceColumn: ExtractDate

		variation Variation
			isDefault
			relationship: a949d721-1875-4375-81a8-6d2ee59516b3
			defaultHierarchy: LocalDateTable_ceeff42a-21b6-4e91-ad14-4e538139bd0a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column ShiftStartSlot
		dataType: string
		lineageTag: 7e74d800-7754-44e1-8595-5ac40c6f185b
		summarizeBy: none
		sourceColumn: ShiftStartSlot

		annotation SummarizationSetBy = Automatic

	column MealBreakTime
		dataType: int64
		formatString: 0
		displayFolder: Duration
		lineageTag: a00b4405-46ca-40ec-851e-e2c8e2cb70f0
		summarizeBy: sum
		sourceColumn: MealBreakTime

		annotation SummarizationSetBy = Automatic

	column TotalShiftDurationMins
		dataType: int64
		formatString: 0
		lineageTag: 921a6141-0062-4a0e-a19b-63c85bb5976c
		summarizeBy: sum
		sourceColumn: TotalShiftDurationMins

		annotation SummarizationSetBy = Automatic

	column ShiftWorkedDurationMins
		dataType: int64
		formatString: 0
		lineageTag: 4ddaf68f-e4b8-4c99-9d97-de7400291462
		summarizeBy: sum
		sourceColumn: ShiftWorkedDurationMins

		annotation SummarizationSetBy = Automatic

	partition 'Fact Shift' = m
		mode: import
		queryGroup: Shifts
		source =
				let
				    Source = Sql.Database("10.2.0.5\azhrinkuat,50660", "HRLink", [Query="SELECT#(lf)#(tab)s.ShiftId#(lf)#(tab),s.AgencyID#(lf)#(tab),s.ClientId#(lf)#(tab),s.MemberID#(lf)#(tab),s.InvoiceID#(lf)#(tab),s.PayslipID#(lf)#(tab),s.CampusId#(lf)#(tab),s.StartDate#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)AS [StartDateTime]#(lf)#(tab),s.FinishDate#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)AS [FinishDateTime]#(lf)#(tab),CAST(s.StartDate AS DATE)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)AS [StartDate]#(lf)#(tab),CAST(s.FinishDate AS DATE)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)AS [FinishDate]#(lf)#(tab),DATEDIFF(MINUTE, s.StartDate, s.FinishDate)#(tab)AS [TotalShiftDurationMins]#(lf)#(tab),DATEDIFF(MINUTE, s.StartDate, s.FinishDate) - s.MealBreakTime#(tab)AS [ShiftWorkedDurationMins]#(lf)#(tab),s.PayHrsPaid1#(lf)#(tab),s.PayRate1#(lf)#(tab),s.PayAmount1#(lf)#(tab),s.PayHrsPaid2#(lf)#(tab),s.PayRate2#(lf)#(tab),s.PayAmount2#(lf)#(tab),s.PaidMealBreakStatus#(lf)    ,s.MealBreakTime#(lf)#(tab),s.OrderedBy#(lf)#(tab),dbo.FirstUpdateForShift(s.ShiftId)#(tab)#(tab)#(tab)#(tab)AS ShiftCreated#(lf)#(tab),s.ConfirmedDate#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)AS ShiftConfirmed#(lf)#(tab)--,dbo.TimeConfirmedClient(s.ShiftID)#(tab)#(tab)#(tab)#(tab)AS TimeConfirmedClient#(lf)#(tab)--,dbo.AllocatorConfirmedClient(s.ShiftId)#(tab)#(tab)AS AllocatorConfirmedClient#(lf)#(tab)--,dbo.TimeConfirmedMember(s.ShiftID)#(tab)#(tab)#(tab)#(tab)AS TimeConfirmedMember#(lf)#(tab)--,dbo.AllocatorConfirmedMember(s.ShiftId)#(tab)#(tab)AS AllocatorConfirmedMember#(lf)#(tab)--,dbo.TimeConfirmedMemberAndClient(s.ShiftID)#(tab)AS TimeConfirmedMemberAndClient#(lf)#(tab)--,dbo.AllocatorConfirmedMemberAndClient(s.ShiftId)#(tab)AS AllocatorConfirmedMemberAndClient#(lf)#(tab),dbo.LastUpdateForShift(s.ShiftId)#(tab)#(tab)#(tab)#(tab)AS ShiftLastUpdated#(lf)#(tab),dbo.isEducationShift(s.ShiftID)#(tab)#(tab)#(tab)#(tab)AS [EducationShiftFlag]#(lf)#(tab),o.description#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)AS [Outcome]#(lf)#(tab),GETDATE()#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)AS [ExtractDate]#(lf)#(tab),dbo.ShiftSlot(s.StartDate)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)AS [ShiftStartSlot]#(lf)FROM dbo.Shift s#(lf)LEFT JOIN (#(lf)#(tab)select *#(lf)#(tab)from dbo.decode #(lf)#(tab)where category = 'Outcome'#(lf)) o on s.OutcomeType = o.value#(lf)where s.AgencyID = 4 AND#(lf)#(tab)(s.MemberID <> 1 OR s.MemberID IS NULL) and#(lf)#(tab)s.StartDate >= DATEADD(year,-3,GETDATE())"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"StartDate", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

