table 'Fill rate map legend'
	lineageTag: 48bccbd1-6894-405d-a8ab-fd08f79ec243

	column Value
		dataType: string
		lineageTag: b2505e57-00a6-41a2-b6a8-a47270b55962
		summarizeBy: none
		sourceColumn: Value
		sortByColumn: Order

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Order
		dataType: int64
		formatString: 0
		lineageTag: 33615d69-3d56-4aa8-a0c8-dd76702fc4f2
		summarizeBy: sum
		sourceColumn: Order

		annotation SummarizationSetBy = Automatic

	partition 'Fill rate map legend' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W8skvTy0uUdJRMlCK1YlW8s1MAbINwWyPzPQMiJyRUmwsAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Value = _t, Order = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Value", type text}, {"Order", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

