table 'Dim Calculation Semantic Model'
	lineageTag: 773c10e2-5826-4094-b7c7-da3c50bae1ac

	column ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 11a1c53c-fbf9-417c-b5cc-0f0555e75550
		summarizeBy: none
		sourceColumn: ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Semantic Model'
		dataType: string
		lineageTag: 014ad381-1e96-4354-b052-9f87211a0af6
		summarizeBy: none
		sourceColumn: Semantic Model

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Dim Calculation Semantic Model' = m
		mode: import
		queryGroup: 'Utilities\Data Dictionary'
		source =
				let
				    Source = #"Data Dictionary - Source",
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"ID", "Semantic Model"}),
				    #"Expanded Semantic Model" = Table.ExpandListColumn(#"Removed Other Columns", "Semantic Model")
				in
				    #"Expanded Semantic Model"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

