table DimVHCUnclaimedVisits
	lineageTag: 57cd7771-d0fe-4025-bc5a-975fc60db3e6

	measure CountUnclaimedVisitRegister = CALCULATE(COUNTROWS(DimVHCUnclaimedVisits), CROSSFILTER(DimVHCUnclaimedVisits[VisitId], FactVisit[visit_id], Both))
		formatString: 0
		lineageTag: 835b8e2b-9dc5-49e6-8699-0b6c9dd9c954

	measure CountClaimedVisits = CALCULATE([CountUnclaimedVisitRegister], DimVHCUnclaimedVisits[RemittancePaidDate] <> BLANK())
		formatString: 0
		lineageTag: 74d3ab9d-a863-48aa-8d0b-d531af26e973

	measure CountUnclaimedVisits = CALCULATE([CountUnclaimedVisitRegister], DimVHCUnclaimedVisits[RemittancePaidDate] = BLANK())
		formatString: 0
		lineageTag: 46d829a2-330b-4b03-bf45-28846fe86e3a

	column DeliveryDate
		dataType: dateTime
		formatString: d/m/yyyy
		lineageTag: 4a9cd21a-16b9-4fb0-a9b7-b6f09daa650a
		summarizeBy: none
		sourceColumn: DeliveryDate

		variation Variation
			isDefault
			relationship: e495511d-a2bf-4d75-86d6-cdbb6567c452
			defaultHierarchy: LocalDateTable_e232ce05-e96c-4940-8165-ddcb5ba57d47.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column BillableCode?
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: fb75eca0-b1a4-4116-a648-c44d6cfee64d
		summarizeBy: none
		sourceColumn: BillableCode?

		annotation SummarizationSetBy = Automatic

	column UpdatedVisitDuration
		dataType: int64
		formatString: 0
		lineageTag: 6a793360-6494-480b-9230-6247565d3187
		summarizeBy: sum
		sourceColumn: UpdatedVisitDuration

		annotation SummarizationSetBy = Automatic

	column Variance
		dataType: decimal
		formatString: \$#,0.###############;-\$#,0.###############;\$#,0.###############
		lineageTag: 955f1f37-860b-4ae3-a20c-420964535eec
		summarizeBy: sum
		sourceColumn: Variance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-AU"}

	column FinanceTeamComments
		dataType: string
		lineageTag: 99ceee79-94c3-4b09-bcbc-34b897963867
		summarizeBy: none
		sourceColumn: FinanceTeamComments

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: dateTime
		formatString: General Date
		lineageTag: ca4059ba-71c4-4c68-a94a-353dc79ad888
		summarizeBy: none
		sourceColumn: Created

		variation Variation
			isDefault
			relationship: aa68dee0-135c-4151-9535-77cb7eee7cc2
			defaultHierarchy: LocalDateTable_1ed6478e-e875-458f-ad12-c0366d921160.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Modified
		dataType: dateTime
		formatString: General Date
		lineageTag: c384f3c1-16f6-4ab6-b3a5-3e5f7003c4f5
		summarizeBy: none
		sourceColumn: Modified

		variation Variation
			isDefault
			relationship: 509f18d9-e1e2-42a4-9632-23a077a3f9c3
			defaultHierarchy: LocalDateTable_05d2b9d5-a93d-4e9a-9394-a51ace876688.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column VisitId
		dataType: int64
		formatString: 0
		lineageTag: 61f83794-b02b-4c9f-af1c-fcc1f31d7c2f
		summarizeBy: none
		sourceColumn: VisitId

		annotation SummarizationSetBy = Automatic

	column DVANumber
		dataType: string
		lineageTag: 733ffe45-4cfc-4893-8e09-29822d4fcb49
		summarizeBy: none
		sourceColumn: DVANumber

		annotation SummarizationSetBy = Automatic

	column ClaimedDate
		dataType: dateTime
		formatString: d/m/yyyy
		lineageTag: 32eed1a4-9e7c-45bf-899a-83befdb5c21f
		summarizeBy: none
		sourceColumn: ClaimedDate

		variation Variation
			isDefault
			relationship: e4085661-a9dd-47ff-9755-1726653a4875
			defaultHierarchy: LocalDateTable_eef661f4-c510-43e9-b1ca-80b01b83aee6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column RemittancePaidDate
		dataType: dateTime
		formatString: d/m/yyyy
		lineageTag: ba89f0f9-1582-4500-852f-04b2c8fa231a
		summarizeBy: none
		sourceColumn: RemittancePaidDate

		variation Variation
			isDefault
			relationship: 7f2fad83-69aa-4062-bf13-f0e56699f1c7
			defaultHierarchy: LocalDateTable_125e8469-728e-4d66-bb75-544c6a2feece.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	partition DimVHCUnclaimedVisits = m
		mode: import
		queryGroup: Claims
		source =
				let
				    Source = #"DimVHCUnclaimedVisits-Source",
				    #"Removed Columns" = Table.RemoveColumns(Source,{"FieldValuesAsText"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

