table 'Fact Calculations'
	isHidden
	lineageTag: deb19d0d-01c1-4fc9-811c-d7395eadd67e

	column ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 37b33751-374a-483b-b884-5bab5645adc2
		summarizeBy: none
		sourceColumn: ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 60472b6f-5eff-4606-9fff-08630ee41f03
		summarizeBy: none
		sourceColumn: Created

		variation Variation
			isDefault
			relationship: 02bb1080-5168-450d-b810-984019da3abd
			defaultHierarchy: LocalDateTable_8caa365c-1a13-4999-8f69-6194cb6cc959.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Modified
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 4817de6b-8d51-450c-909d-76a901210f47
		summarizeBy: none
		sourceColumn: Modified

		variation Variation
			isDefault
			relationship: 975cce6e-9a90-4cb5-b94d-9ded13040bb1
			defaultHierarchy: LocalDateTable_a3a133dc-5edb-42a0-b1bb-c7003d8c5c9e.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Version
		dataType: string
		isHidden
		lineageTag: 6c6a5626-674d-4210-9ffd-9cab4ed3ebf5
		summarizeBy: none
		sourceColumn: Version

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Fact Calculations' = m
		mode: import
		queryGroup: 'Utilities\Data Dictionary'
		source =
				let
				    Source = #"Data Dictionary - Source",
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"ID", "Created", "Modified", "Version"})
				in
				    #"Removed Other Columns"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

