table 'Dim Workforce Duplicates'
	lineageTag: eecaaf06-5c34-48b8-a319-61581a764072

	column 'First name'
		dataType: string
		lineageTag: 54a95b14-3183-4e97-ac05-3270e95432b0
		summarizeBy: none
		sourceColumn: First name

		annotation SummarizationSetBy = Automatic

	column 'Last name'
		dataType: string
		lineageTag: 6bcbfcea-039d-45a0-aae6-8591dd02c271
		summarizeBy: none
		sourceColumn: Last name

		annotation SummarizationSetBy = Automatic

	column 'Employing entity'
		dataType: string
		lineageTag: a654da06-f3bb-4cff-83cf-d2e3daa26d15
		summarizeBy: none
		sourceColumn: Employing entity

		annotation SummarizationSetBy = Automatic

	column 'Employee code'
		dataType: string
		lineageTag: fa982ce8-10c8-48de-bc95-e9680c236ada
		summarizeBy: none
		sourceColumn: Employee code

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: 85323e61-2e4e-4e60-8540-f66d5cb908c7
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column 'Primary cost centre'
		dataType: string
		lineageTag: efff0624-f570-4ef6-b7c2-7fb263dee825
		summarizeBy: none
		sourceColumn: Primary cost centre

		annotation SummarizationSetBy = Automatic

	column 'Primary manager'
		dataType: string
		lineageTag: e256e886-aa93-4928-bfc5-251175c70bd9
		summarizeBy: none
		sourceColumn: Primary manager

		annotation SummarizationSetBy = Automatic

	column 'Length of probation'
		dataType: string
		lineageTag: 3775d9ca-9e43-4d40-b0d6-4a1d0cec9d66
		summarizeBy: none
		sourceColumn: Length of probation

		annotation SummarizationSetBy = Automatic

	column 'Termination type'
		dataType: string
		lineageTag: 6d8d528f-6e18-4a0c-a077-5fdd8ffc7fc6
		summarizeBy: none
		sourceColumn: Termination type

		annotation SummarizationSetBy = Automatic

	column 'Termination reason'
		dataType: string
		lineageTag: eaf257f3-f523-46b8-b86b-489eb063265b
		summarizeBy: none
		sourceColumn: Termination reason

		annotation SummarizationSetBy = Automatic

	column 'Is manager'
		dataType: string
		lineageTag: 186e5d5c-162e-46db-ae76-53dbb68c9399
		summarizeBy: none
		sourceColumn: Is manager

		annotation SummarizationSetBy = Automatic

	column 'Employment status'
		dataType: string
		lineageTag: cb1ac26b-4ace-4678-b0bc-e7568a5ad892
		summarizeBy: none
		sourceColumn: Employment status

		annotation SummarizationSetBy = Automatic

	column 'Onboarding status'
		dataType: string
		lineageTag: 0c90b319-674d-4bf9-bae2-b9d1e5fbdd4f
		summarizeBy: none
		sourceColumn: Onboarding status

		annotation SummarizationSetBy = Automatic

	column 'Visa type'
		dataType: string
		lineageTag: 200304d2-11ab-40cd-9481-4b746aaf768d
		summarizeBy: none
		sourceColumn: Visa type

		annotation SummarizationSetBy = Automatic

	column 'Full name'
		dataType: string
		lineageTag: c6c20f31-ff8f-4714-9b2e-ac808e94c674
		summarizeBy: none
		sourceColumn: Full name

		annotation SummarizationSetBy = Automatic

	column MemberExtractId
		dataType: string
		lineageTag: a0c74733-7076-4502-80ce-e6bd70872e22
		summarizeBy: none
		sourceColumn: MemberExtractId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 1607a841-9665-4845-b095-d9d47573273f
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column 'Employee address postcode'
		dataType: string
		lineageTag: c096a830-addd-486b-b109-f0c251b8f6b8
		dataCategory: PostalCode
		summarizeBy: none
		sourceColumn: Employee address postcode

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column Nationality
		dataType: string
		lineageTag: 8cec8120-4227-4cb3-8472-9667ca1d9172
		summarizeBy: none
		sourceColumn: Nationality

		annotation SummarizationSetBy = Automatic

	column 'Middle name'
		dataType: string
		lineageTag: bb242e94-b53d-4ba9-9962-e64aef061418
		summarizeBy: none
		sourceColumn: Middle name

		annotation SummarizationSetBy = Automatic

	column 'Extract Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: b7add3ee-f554-4967-8bcc-632adf56005c
		summarizeBy: none
		sourceColumn: Extract Date

		variation Variation
			isDefault
			relationship: 7ed5c3d0-58e8-448a-9836-72bcf9516f71
			defaultHierarchy: LocalDateTable_fe7acd62-1fdc-489a-9528-538229f30969.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Source Entity'
		dataType: string
		lineageTag: 45fb5c15-bc4e-4a83-8a40-da950e862d95
		summarizeBy: none
		sourceColumn: Source Entity

		annotation SummarizationSetBy = Automatic

	column 'Account email'
		dataType: string
		lineageTag: b9933eff-fa74-4574-87c0-b36a1620db14
		summarizeBy: none
		sourceColumn: Account email

		annotation SummarizationSetBy = Automatic

	column Groups
		dataType: string
		lineageTag: 0b426bc4-4f41-45e2-8d99-19119fd9dac3
		summarizeBy: none
		sourceColumn: Groups

		annotation SummarizationSetBy = Automatic

	column EmailExtractKey
		dataType: string
		lineageTag: 26572a2e-36f5-423d-b0a3-8178591f2911
		summarizeBy: none
		sourceColumn: EmailExtractKey

		annotation SummarizationSetBy = Automatic

	partition 'Dim Workforce Duplicates' = m
		mode: import
		queryGroup: Workforce
		source =
				let
				    Source = #"Dim Workforce - Source",
				    #"Kept Duplicates" = let columnNames = {"Full name", "Extract Date"}, addCount = Table.Group(Source, columnNames, {{"Count", Table.RowCount, type number}}), selectDuplicates = Table.SelectRows(addCount, each [Count] > 1), removeCount = Table.RemoveColumns(selectDuplicates, "Count") in Table.Join(Source, columnNames, removeCount, columnNames, JoinKind.Inner),
				    #"Renamed Columns" = Table.RenameColumns(#"Kept Duplicates",{{"Member ID", "MemberExtractId"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

