table DimOnboardingRegister
	lineageTag: cdbc6509-6821-4b86-a1a9-1cd57a2c3df5

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 37218239-af83-4da2-8bd0-aaedf3dd3276
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column EmployeeName
		dataType: string
		lineageTag: c815150d-c015-4fdf-9b7d-0a1a2e5a432d
		summarizeBy: none
		sourceColumn: EmployeeName

		annotation SummarizationSetBy = Automatic

	column picture
		dataType: string
		lineageTag: 57160ae7-ee5d-4163-8e01-1418df45340b
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: picture

		annotation SummarizationSetBy = Automatic

	column Division
		dataType: string
		lineageTag: 33f77f41-af3d-443b-b132-7c298023ac5c
		summarizeBy: none
		sourceColumn: Division

		annotation SummarizationSetBy = Automatic

	column 'Re-Onboard/Internal Transfer'
		dataType: string
		lineageTag: 96820bb7-6639-4a8c-860b-80a1971c8e8c
		summarizeBy: none
		sourceColumn: Re-Onboard/Internal Transfer

		annotation SummarizationSetBy = Automatic

	column Groups
		dataType: string
		lineageTag: c6c6d3f1-834a-4491-9805-6e77862b6f98
		summarizeBy: none
		sourceColumn: Groups

		annotation SummarizationSetBy = Automatic

	column PositionTitle
		dataType: string
		lineageTag: 33c408fe-67af-4a10-977c-7722b7c6808e
		summarizeBy: none
		sourceColumn: PositionTitle

		annotation SummarizationSetBy = Automatic

	column Version
		dataType: string
		lineageTag: e77725f1-4948-4c59-bb67-c3552432607e
		summarizeBy: none
		sourceColumn: Version

		annotation SummarizationSetBy = Automatic

	column 'State Acronym'
		dataType: string
		lineageTag: 509a95e3-4eea-4e7f-8145-02a897954084
		summarizeBy: none
		sourceColumn: State Acronym

		annotation SummarizationSetBy = Automatic

	column 'Work Location'
		dataType: string
		lineageTag: 944d7619-9e44-4fe3-a2cd-6b14ea9fa45c
		summarizeBy: none
		sourceColumn: Work Location

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: dbfc330a-b8d4-4244-83fb-6864a54dcb64
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	partition DimOnboardingRegister = m
		mode: import
		queryGroup: Onboarding
		source =
				let
				    Source = #"Onboarding Register - Source",
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"ID", "Employee Name", "Division", "Work Location", "Position Title", "Re-Onboard/Internal Transfer", "Groups", "State", "Version"}),
				    #"Expanded Employee Name" = Table.ExpandListColumn(#"Removed Other Columns", "Employee Name"),
				    #"Expanded Employee Name1" = Table.ExpandRecordColumn(#"Expanded Employee Name", "Employee Name", {"title", "picture"}, {"EmployeeName", "picture"}),
				    #"Expanded Position Title" = Table.ExpandListColumn(#"Expanded Employee Name1", "Position Title"),
				    #"Expanded Position Title1" = Table.ExpandRecordColumn(#"Expanded Position Title", "Position Title", {"lookupValue"}, {"PositionTitle"}),
				    #"Expanded Work Location" = Table.ExpandListColumn(#"Expanded Position Title1", "Work Location"),
				    #"Expanded Work Location1" = Table.ExpandRecordColumn(#"Expanded Work Location", "Work Location", {"lookupValue"}, {"Work Location"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Work Location1",{{"Work Location", type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type","",null,Replacer.ReplaceValue,{"Groups", "State"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","0",null,Replacer.ReplaceValue,{"Re-Onboard/Internal Transfer"}),
				    #"Added Conditional Column" = Table.AddColumn(#"Replaced Value1", "State Acronym", each if [State] = "South Australia" then "SA" else if [State] = "Queensland" then "QLD" else if [State] = "Victoria" then "VIC" else if [State] = "New South Wales" then "NSW" else if [State] = "Western Australia" then "WA" else if [State] = "Northern Territory" then "NT" else if [State] = "Tasmania" then "TAS" else if [State] = "Australian Capital Territory" then "ACT" else [State])
				in
				    #"Added Conditional Column"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

