table 'Fact Calculations'
	isHidden
	lineageTag: ba792ba9-1e1d-41a2-aefa-91cdf7ccf613

	column ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 1a279866-f6fa-40ab-be02-769bd3159ea8
		summarizeBy: none
		sourceColumn: ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: afdf23bf-b7a0-49f9-ba53-1379eb3e8806
		summarizeBy: none
		sourceColumn: Created

		variation Variation
			isDefault
			relationship: f26f3169-5151-4f5d-a3e6-b89e3b51c7e3
			defaultHierarchy: LocalDateTable_61cc6fe0-1f6c-4f16-b13b-80f9e9e9aa0b.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Modified
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: e55c5395-a85c-4ee0-902e-8d0b7a81c20a
		summarizeBy: none
		sourceColumn: Modified

		variation Variation
			isDefault
			relationship: b89c4ed6-ca06-4844-87d3-05f6e375278a
			defaultHierarchy: LocalDateTable_5adf32fc-0583-4c6a-a252-da57b63016e0.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Version
		dataType: string
		isHidden
		lineageTag: 5be0a52a-b40e-465e-bab1-04a074578a00
		summarizeBy: none
		sourceColumn: Version

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Fact Calculations' = m
		mode: import
		queryGroup: 'Utilities\Data Dictionary'
		source =
				let
				    Source = #"Data Dictionary - Source",
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"ID", "Created", "Modified", "Version"})
				in
				    #"Removed Other Columns"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

